version: '3'
services:
  pbs:
    tmpfs:
      - /run
    build: .
    environment:
      - MSMTP_HOST
      - MSMTP_PORT
      - MSMTP_TLS
      - MSMTP_STARTTLS
      - MSMTP_TLSCHECK
      - MSMTP_AUTH
      - MSMTP_USER
      - MSMTP_PASSWORD
      - MSMTP_FROM
      - PBS_ADMIN_PASSWORD
    ports:
     - "8007:8007"
    volumes:
      - pbs_etc:/etc/proxmox-backup
      - pbs_log:/var/log/proxmox-backup
      - pbs_lib:/var/lib/proxmox-backup
      - pbs_backups:/backups

volumes:
  pbs_etc:
  pbs_log:
  pbs_lib:
  pbs_backups:
